theme: jekyll-theme-minimal
name: Cameyoox
title: Cameyoox
description:
  uk: Score the best deals in Yoox
  es: Consigue las mejores ofertas en Yoox
  us: Score the best deals in Yoox
twitter:
  username: cameyoox
  card: summary
logo: favicon.ico
social:
  name: Cameyoox
  links:
    - https://twitter.com/cameyoox
    - https://www.instagram.com/cameyoox
    - https://www.facebook.com/Cameyoox-108763624616741
locale: en

analytics_uk: G-361FNV75S6
analytics_es: G-7K8GZB7G3T
analytics_us: G-B42YT4EGMJ

plugins:
  - jekyll-sitemap